---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: udagram-web
  name: udagram-web
  namespace: default
  selfLink: /api/v1/namespaces/default/services/udagram-web
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: udagram-web
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
    
    
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-web
  labels:
    app: udagram-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-web
  template:
    metadata:
      labels:
        app: udagram-web
    spec:
      containers:
      - image: robertofrontado/udagram-web
        name: udagram-web
        ports:
        - containerPort: 80
        imagePullPolicy: Always
            